config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about", as: "about"
  resources :books
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  
   
has_one_attached :profile_image
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end


  
  def after_sign_out_path_for(resource)
    about_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end
  
  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   @book.save
   redirect_to book_path(@book.id)
   flash[:notice] =  'You have created book successfully.'
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = 'You have updated book successfully.'
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  def index
    @books =Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    
  end
  
  def index
  end

  def new
  end

  def edit
    @user = User.find_by(id: session[:user_id])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-mod-3">
  
  <h2>User info</h2>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th></th>
      </tr>
    </tbody>
  </table>
  <div class="row"><% link_to "Edit", edit_user_path(current_user.id) %></div>

<h2>New book</h2>
<%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_field :body %>
    
    <br><%= f.submit 'Create Book' %></br>
  <% end %>
  </div>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<%= render 'list', book: @book %>

<div class="col-md-8 offset-md-1">
    
    <h2>Books</h2>
<table class ="table table-hover table-inverse">
    <thread>
        <tr>
        <th></th>
        <th>Title</th>
        
        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
    </thread>
    <% @books.each do |book| %>
    
    
    <tbody>
    <tr>
      <td></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure ?" %></td>
    </tr>
    </tbody><% end %>
</table>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<h1>Welcome to
        <strong>Bookers</strong>!!
</h1>

app/views/homes/top.html.erb
<main>
  <p id="notice">Signed out successfully.</p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to
        <strong>Bookers</strong>!!
        </h1>
        <p>In
        <strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
     <li>
       <%= link_to 'Home', user_path(current_user.id) %>
     </li>
     <li>
       <a class="Users" href="/users">Users</a>
     </li>
     <li>
       <a class='Books' href="/books">Books</a>
     </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
       <a class="Home" href="">Home</a>
     </li>
     <li>
       <a class='About' href="/homes/about">About</a>
     </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
      
    <% end %>
  </header>
  
  <footer>
    <div class="container mt-5">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <label for="user_image">Image</label>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="form-group">
    <label for="user_introduction">Introduction</label>
    <%= f.text_field :introduction %>
  </div>
  <div class="form-group">
    <%= f.submit "Update User" %>
    
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="col-mod-3">
  <h3>User　info</h3>
  <%= image_tag @user.get_profile_image(100,100) %>
</div>